# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import XataClient
from XataClient.models.one_of_filter_predicate_op_not import OneOfFilterPredicateOpNot  # noqa: E501
from XataClient.rest import ApiException


class TestOneOfFilterPredicateOpNot(unittest.TestCase):
    """OneOfFilterPredicateOpNot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfFilterPredicateOpNot(self):
        """Test OneOfFilterPredicateOpNot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XataClient.models.one_of_filter_predicate_op_not.OneOfFilterPredicateOpNot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
