# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.database_api import DatabaseApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDatabaseApi(unittest.TestCase):
    """DatabaseApi unit test stubs"""

    def setUp(self):
        self.api = DatabaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_database(self):
        """Test case for create_database

        Create Database  # noqa: E501
        """
        pass

    def test_delete_database(self):
        """Test case for delete_database

        Delete Database  # noqa: E501
        """
        pass

    def test_get_database_list(self):
        """Test case for get_database_list

        List databases  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
