# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response4001_errors import InlineResponse4001Errors  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse4001Errors(unittest.TestCase):
    """InlineResponse4001Errors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4001Errors(self):
        """Test InlineResponse4001Errors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response4001_errors.InlineResponse4001Errors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
