# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_filter_list import OneOfFilterList  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfFilterList(unittest.TestCase):
    """OneOfFilterList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfFilterList(self):
        """Test OneOfFilterList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_filter_list.OneOfFilterList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
