# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import XataClient
from XataClient.models.list_databases_response_databases import ListDatabasesResponseDatabases  # noqa: E501
from XataClient.rest import ApiException


class TestListDatabasesResponseDatabases(unittest.TestCase):
    """ListDatabasesResponseDatabases unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListDatabasesResponseDatabases(self):
        """Test ListDatabasesResponseDatabases"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XataClient.models.list_databases_response_databases.ListDatabasesResponseDatabases()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
