# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.branch_metadata import BranchMetadata  # noqa: E501
from swagger_client.rest import ApiException


class TestBranchMetadata(unittest.TestCase):
    """BranchMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBranchMetadata(self):
        """Test BranchMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.branch_metadata.BranchMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
