# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.filter_predicate import FilterPredicate  # noqa: E501
from swagger_client.rest import ApiException


class TestFilterPredicate(unittest.TestCase):
    """FilterPredicate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterPredicate(self):
        """Test FilterPredicate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.filter_predicate.FilterPredicate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
