# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response200_keys import InlineResponse200Keys  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse200Keys(unittest.TestCase):
    """InlineResponse200Keys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200Keys(self):
        """Test InlineResponse200Keys"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response200_keys.InlineResponse200Keys()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
