# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.filter_range_value import FilterRangeValue  # noqa: E501
from swagger_client.rest import ApiException


class TestFilterRangeValue(unittest.TestCase):
    """FilterRangeValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterRangeValue(self):
        """Test FilterRangeValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.filter_range_value.FilterRangeValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
