# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import XataClient
from XataClient.models.one_of_filter_predicate_op_is_not import OneOfFilterPredicateOpIsNot  # noqa: E501
from XataClient.rest import ApiException


class TestOneOfFilterPredicateOpIsNot(unittest.TestCase):
    """OneOfFilterPredicateOpIsNot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfFilterPredicateOpIsNot(self):
        """Test OneOfFilterPredicateOpIsNot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XataClient.models.one_of_filter_predicate_op_is_not.OneOfFilterPredicateOpIsNot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
