# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import XataClient
from XataClient.models.db_branch import DBBranch  # noqa: E501
from XataClient.rest import ApiException


class TestDBBranch(unittest.TestCase):
    """DBBranch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDBBranch(self):
        """Test DBBranch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XataClient.models.db_branch.DBBranch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
