# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import XataClient
from XataClient.api.table_api import TableApi  # noqa: E501
from XataClient.rest import ApiException


class TestTableApi(unittest.TestCase):
    """TableApi unit test stubs"""

    def setUp(self):
        self.api = TableApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_table_column(self):
        """Test case for add_table_column

        Creates a new column  # noqa: E501
        """
        pass

    def test_create_table(self):
        """Test case for create_table

        Create table  # noqa: E501
        """
        pass

    def test_delete_column(self):
        """Test case for delete_column

        Deletes a column  # noqa: E501
        """
        pass

    def test_delete_table(self):
        """Test case for delete_table

        Delete table  # noqa: E501
        """
        pass

    def test_get_column(self):
        """Test case for get_column

        Get column information  # noqa: E501
        """
        pass

    def test_get_table_columns(self):
        """Test case for get_table_columns

        Get the columns  # noqa: E501
        """
        pass

    def test_get_table_schema(self):
        """Test case for get_table_schema

        Get table schema  # noqa: E501
        """
        pass

    def test_set_table_schema(self):
        """Test case for set_table_schema

        Update table schema  # noqa: E501
        """
        pass

    def test_update_column(self):
        """Test case for update_column

        Updates a column  # noqa: E501
        """
        pass

    def test_update_table(self):
        """Test case for update_table

        Update table  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
