# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import XataClient
from XataClient.models.one_of_filter_value import OneOfFilterValue  # noqa: E501
from XataClient.rest import ApiException


class TestOneOfFilterValue(unittest.TestCase):
    """OneOfFilterValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfFilterValue(self):
        """Test OneOfFilterValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XataClient.models.one_of_filter_value.OneOfFilterValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
