# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import XataClient
from XataClient.models.inline_response4001 import InlineResponse4001  # noqa: E501
from XataClient.rest import ApiException


class TestInlineResponse4001(unittest.TestCase):
    """InlineResponse4001 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4001(self):
        """Test InlineResponse4001"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XataClient.models.inline_response4001.InlineResponse4001()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
