# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2012_xata import InlineResponse2012Xata  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2012Xata(unittest.TestCase):
    """InlineResponse2012Xata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2012Xata(self):
        """Test InlineResponse2012Xata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2012_xata.InlineResponse2012Xata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
