# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.filter_predicate_range_op import FilterPredicateRangeOp  # noqa: E501
from swagger_client.rest import ApiException


class TestFilterPredicateRangeOp(unittest.TestCase):
    """FilterPredicateRangeOp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterPredicateRangeOp(self):
        """Test FilterPredicateRangeOp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.filter_predicate_range_op.FilterPredicateRangeOp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
