# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import XataClient
from XataClient.models.workspace_id_invites_body import WorkspaceIdInvitesBody  # noqa: E501
from XataClient.rest import ApiException


class TestWorkspaceIdInvitesBody(unittest.TestCase):
    """WorkspaceIdInvitesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceIdInvitesBody(self):
        """Test WorkspaceIdInvitesBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = XataClient.models.workspace_id_invites_body.WorkspaceIdInvitesBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
