# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.branch_api import BranchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBranchApi(unittest.TestCase):
    """BranchApi unit test stubs"""

    def setUp(self):
        self.api = BranchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_branch(self):
        """Test case for create_branch

        Create Database branch  # noqa: E501
        """
        pass

    def test_delete_branch(self):
        """Test case for delete_branch

        Delete Database branch  # noqa: E501
        """
        pass

    def test_execute_branch_migration_plan(self):
        """Test case for execute_branch_migration_plan

        Migrate branch  # noqa: E501
        """
        pass

    def test_get_branch_details(self):
        """Test case for get_branch_details

        Get branch schema and metadata  # noqa: E501
        """
        pass

    def test_get_branch_list(self):
        """Test case for get_branch_list

        List branches  # noqa: E501
        """
        pass

    def test_get_branch_metadata(self):
        """Test case for get_branch_metadata

        Get Branch Metadata  # noqa: E501
        """
        pass

    def test_get_branch_migration_history(self):
        """Test case for get_branch_migration_history

        Get branch migration history  # noqa: E501
        """
        pass

    def test_get_branch_migration_plan(self):
        """Test case for get_branch_migration_plan

        Compute migration plan  # noqa: E501
        """
        pass

    def test_get_branch_stats(self):
        """Test case for get_branch_stats

        Branch stats  # noqa: E501
        """
        pass

    def test_update_branch_metadata(self):
        """Test case for update_branch_metadata

        Update branch metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
