# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.dbs_db_name_body import DbsDbNameBody  # noqa: E501
from swagger_client.rest import ApiException


class TestDbsDbNameBody(unittest.TestCase):
    """DbsDbNameBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbsDbNameBody(self):
        """Test DbsDbNameBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dbs_db_name_body.DbsDbNameBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
