# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_api_key(self):
        """Test case for create_user_api_key

        Create and return new API key  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete user  # noqa: E501
        """
        pass

    def test_delete_user_api_key(self):
        """Test case for delete_user_api_key

        Delete an existing API key  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get user details  # noqa: E501
        """
        pass

    def test_get_user_api_keys(self):
        """Test case for get_user_api_keys

        Get the list of user API keys  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update user info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
