# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.db_db_branch_name_body import DbDbBranchNameBody  # noqa: E501
from swagger_client.rest import ApiException


class TestDbDbBranchNameBody(unittest.TestCase):
    """DbDbBranchNameBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDbDbBranchNameBody(self):
        """Test DbDbBranchNameBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.db_db_branch_name_body.DbDbBranchNameBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
