# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FilterPredicateRangeOp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lt': 'FilterRangeValue',
        'le': 'FilterRangeValue',
        'gt': 'FilterRangeValue',
        'ge': 'FilterRangeValue'
    }

    attribute_map = {
        'lt': '$lt',
        'le': '$le',
        'gt': '$gt',
        'ge': '$ge'
    }

    def __init__(self, lt=None, le=None, gt=None, ge=None):  # noqa: E501
        """FilterPredicateRangeOp - a model defined in Swagger"""  # noqa: E501
        self._lt = None
        self._le = None
        self._gt = None
        self._ge = None
        self.discriminator = None
        if lt is not None:
            self.lt = lt
        if le is not None:
            self.le = le
        if gt is not None:
            self.gt = gt
        if ge is not None:
            self.ge = ge

    @property
    def lt(self):
        """Gets the lt of this FilterPredicateRangeOp.  # noqa: E501


        :return: The lt of this FilterPredicateRangeOp.  # noqa: E501
        :rtype: FilterRangeValue
        """
        return self._lt

    @lt.setter
    def lt(self, lt):
        """Sets the lt of this FilterPredicateRangeOp.


        :param lt: The lt of this FilterPredicateRangeOp.  # noqa: E501
        :type: FilterRangeValue
        """

        self._lt = lt

    @property
    def le(self):
        """Gets the le of this FilterPredicateRangeOp.  # noqa: E501


        :return: The le of this FilterPredicateRangeOp.  # noqa: E501
        :rtype: FilterRangeValue
        """
        return self._le

    @le.setter
    def le(self, le):
        """Sets the le of this FilterPredicateRangeOp.


        :param le: The le of this FilterPredicateRangeOp.  # noqa: E501
        :type: FilterRangeValue
        """

        self._le = le

    @property
    def gt(self):
        """Gets the gt of this FilterPredicateRangeOp.  # noqa: E501


        :return: The gt of this FilterPredicateRangeOp.  # noqa: E501
        :rtype: FilterRangeValue
        """
        return self._gt

    @gt.setter
    def gt(self, gt):
        """Sets the gt of this FilterPredicateRangeOp.


        :param gt: The gt of this FilterPredicateRangeOp.  # noqa: E501
        :type: FilterRangeValue
        """

        self._gt = gt

    @property
    def ge(self):
        """Gets the ge of this FilterPredicateRangeOp.  # noqa: E501


        :return: The ge of this FilterPredicateRangeOp.  # noqa: E501
        :rtype: FilterRangeValue
        """
        return self._ge

    @ge.setter
    def ge(self, ge):
        """Sets the ge of this FilterPredicateRangeOp.


        :param ge: The ge of this FilterPredicateRangeOp.  # noqa: E501
        :type: FilterRangeValue
        """

        self._ge = ge

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FilterPredicateRangeOp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FilterPredicateRangeOp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
