# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MigrationsExecuteBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'int',
        'migration': 'BranchMigration'
    }

    attribute_map = {
        'version': 'version',
        'migration': 'migration'
    }

    def __init__(self, version=None, migration=None):  # noqa: E501
        """MigrationsExecuteBody - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._migration = None
        self.discriminator = None
        self.version = version
        self.migration = migration

    @property
    def version(self):
        """Gets the version of this MigrationsExecuteBody.  # noqa: E501


        :return: The version of this MigrationsExecuteBody.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this MigrationsExecuteBody.


        :param version: The version of this MigrationsExecuteBody.  # noqa: E501
        :type: int
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def migration(self):
        """Gets the migration of this MigrationsExecuteBody.  # noqa: E501


        :return: The migration of this MigrationsExecuteBody.  # noqa: E501
        :rtype: BranchMigration
        """
        return self._migration

    @migration.setter
    def migration(self, migration):
        """Sets the migration of this MigrationsExecuteBody.


        :param migration: The migration of this MigrationsExecuteBody.  # noqa: E501
        :type: BranchMigration
        """
        if migration is None:
            raise ValueError("Invalid value for `migration`, must not be `None`")  # noqa: E501

        self._migration = migration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MigrationsExecuteBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MigrationsExecuteBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
