# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecordXata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'int',
        'table': 'str',
        'warnings': 'list[str]'
    }

    attribute_map = {
        'version': 'version',
        'table': 'table',
        'warnings': 'warnings'
    }

    def __init__(self, version=None, table=None, warnings=None):  # noqa: E501
        """RecordXata - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._table = None
        self._warnings = None
        self.discriminator = None
        self.version = version
        if table is not None:
            self.table = table
        if warnings is not None:
            self.warnings = warnings

    @property
    def version(self):
        """Gets the version of this RecordXata.  # noqa: E501

        The record's version. Can be used for optimistic concurrency control.  # noqa: E501

        :return: The version of this RecordXata.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this RecordXata.

        The record's version. Can be used for optimistic concurrency control.  # noqa: E501

        :param version: The version of this RecordXata.  # noqa: E501
        :type: int
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def table(self):
        """Gets the table of this RecordXata.  # noqa: E501

        The record's table name. APIs that return records from multiple tables will set _table accordingly.  # noqa: E501

        :return: The table of this RecordXata.  # noqa: E501
        :rtype: str
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this RecordXata.

        The record's table name. APIs that return records from multiple tables will set _table accordingly.  # noqa: E501

        :param table: The table of this RecordXata.  # noqa: E501
        :type: str
        """

        self._table = table

    @property
    def warnings(self):
        """Gets the warnings of this RecordXata.  # noqa: E501

        Encoding/Decoding errors  # noqa: E501

        :return: The warnings of this RecordXata.  # noqa: E501
        :rtype: list[str]
        """
        return self._warnings

    @warnings.setter
    def warnings(self, warnings):
        """Sets the warnings of this RecordXata.

        Encoding/Decoding errors  # noqa: E501

        :param warnings: The warnings of this RecordXata.  # noqa: E501
        :type: list[str]
        """

        self._warnings = warnings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecordXata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecordXata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
