# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Schema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tables': 'list[Table]',
        'tables_order': 'list[str]'
    }

    attribute_map = {
        'tables': 'tables',
        'tables_order': 'tablesOrder'
    }

    def __init__(self, tables=None, tables_order=None):  # noqa: E501
        """Schema - a model defined in Swagger"""  # noqa: E501
        self._tables = None
        self._tables_order = None
        self.discriminator = None
        self.tables = tables
        if tables_order is not None:
            self.tables_order = tables_order

    @property
    def tables(self):
        """Gets the tables of this Schema.  # noqa: E501


        :return: The tables of this Schema.  # noqa: E501
        :rtype: list[Table]
        """
        return self._tables

    @tables.setter
    def tables(self, tables):
        """Sets the tables of this Schema.


        :param tables: The tables of this Schema.  # noqa: E501
        :type: list[Table]
        """
        if tables is None:
            raise ValueError("Invalid value for `tables`, must not be `None`")  # noqa: E501

        self._tables = tables

    @property
    def tables_order(self):
        """Gets the tables_order of this Schema.  # noqa: E501


        :return: The tables_order of this Schema.  # noqa: E501
        :rtype: list[str]
        """
        return self._tables_order

    @tables_order.setter
    def tables_order(self, tables_order):
        """Sets the tables_order of this Schema.


        :param tables_order: The tables_order of this Schema.  # noqa: E501
        :type: list[str]
        """

        self._tables_order = tables_order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Schema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Schema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
