# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TableNameQueryBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filter': 'FilterExpression',
        'sort': 'SortExpression',
        'page': 'PageConfig',
        'columns': 'ColumnsFilter'
    }

    attribute_map = {
        'filter': 'filter',
        'sort': 'sort',
        'page': 'page',
        'columns': 'columns'
    }

    def __init__(self, filter=None, sort=None, page=None, columns=None):  # noqa: E501
        """TableNameQueryBody - a model defined in Swagger"""  # noqa: E501
        self._filter = None
        self._sort = None
        self._page = None
        self._columns = None
        self.discriminator = None
        if filter is not None:
            self.filter = filter
        if sort is not None:
            self.sort = sort
        if page is not None:
            self.page = page
        if columns is not None:
            self.columns = columns

    @property
    def filter(self):
        """Gets the filter of this TableNameQueryBody.  # noqa: E501


        :return: The filter of this TableNameQueryBody.  # noqa: E501
        :rtype: FilterExpression
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this TableNameQueryBody.


        :param filter: The filter of this TableNameQueryBody.  # noqa: E501
        :type: FilterExpression
        """

        self._filter = filter

    @property
    def sort(self):
        """Gets the sort of this TableNameQueryBody.  # noqa: E501


        :return: The sort of this TableNameQueryBody.  # noqa: E501
        :rtype: SortExpression
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this TableNameQueryBody.


        :param sort: The sort of this TableNameQueryBody.  # noqa: E501
        :type: SortExpression
        """

        self._sort = sort

    @property
    def page(self):
        """Gets the page of this TableNameQueryBody.  # noqa: E501


        :return: The page of this TableNameQueryBody.  # noqa: E501
        :rtype: PageConfig
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this TableNameQueryBody.


        :param page: The page of this TableNameQueryBody.  # noqa: E501
        :type: PageConfig
        """

        self._page = page

    @property
    def columns(self):
        """Gets the columns of this TableNameQueryBody.  # noqa: E501


        :return: The columns of this TableNameQueryBody.  # noqa: E501
        :rtype: ColumnsFilter
        """
        return self._columns

    @columns.setter
    def columns(self, columns):
        """Sets the columns of this TableNameQueryBody.


        :param columns: The columns of this TableNameQueryBody.  # noqa: E501
        :type: ColumnsFilter
        """

        self._columns = columns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TableNameQueryBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TableNameQueryBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
