# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.workspace_meta import WorkspaceMeta  # noqa: F401,E501

class Workspace(WorkspaceMeta):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'WorkspaceID',
        'member_count': 'int',
        'plan': 'str'
    }
    if hasattr(WorkspaceMeta, "swagger_types"):
        swagger_types.update(WorkspaceMeta.swagger_types)

    attribute_map = {
        'id': 'id',
        'member_count': 'memberCount',
        'plan': 'plan'
    }
    if hasattr(WorkspaceMeta, "attribute_map"):
        attribute_map.update(WorkspaceMeta.attribute_map)

    def __init__(self, id=None, member_count=None, plan=None, *args, **kwargs):  # noqa: E501
        """Workspace - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._member_count = None
        self._plan = None
        self.discriminator = None
        self.id = id
        self.member_count = member_count
        self.plan = plan
        WorkspaceMeta.__init__(self, *args, **kwargs)

    @property
    def id(self):
        """Gets the id of this Workspace.  # noqa: E501


        :return: The id of this Workspace.  # noqa: E501
        :rtype: WorkspaceID
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Workspace.


        :param id: The id of this Workspace.  # noqa: E501
        :type: WorkspaceID
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def member_count(self):
        """Gets the member_count of this Workspace.  # noqa: E501


        :return: The member_count of this Workspace.  # noqa: E501
        :rtype: int
        """
        return self._member_count

    @member_count.setter
    def member_count(self, member_count):
        """Sets the member_count of this Workspace.


        :param member_count: The member_count of this Workspace.  # noqa: E501
        :type: int
        """
        if member_count is None:
            raise ValueError("Invalid value for `member_count`, must not be `None`")  # noqa: E501

        self._member_count = member_count

    @property
    def plan(self):
        """Gets the plan of this Workspace.  # noqa: E501


        :return: The plan of this Workspace.  # noqa: E501
        :rtype: str
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this Workspace.


        :param plan: The plan of this Workspace.  # noqa: E501
        :type: str
        """
        if plan is None:
            raise ValueError("Invalid value for `plan`, must not be `None`")  # noqa: E501
        allowed_values = ["free"]  # noqa: E501
        if plan not in allowed_values:
            raise ValueError(
                "Invalid value for `plan` ({0}), must be one of {1}"  # noqa: E501
                .format(plan, allowed_values)
            )

        self._plan = plan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Workspace, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Workspace):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
