# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DbsDbNameBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_name': 'str',
        'branch_name': 'str',
        'ui': 'DbsdbNameUi',
        'metadata': 'BranchMetadata'
    }

    attribute_map = {
        'display_name': 'displayName',
        'branch_name': 'branchName',
        'ui': 'ui',
        'metadata': 'metadata'
    }

    def __init__(self, display_name=None, branch_name=None, ui=None, metadata=None):  # noqa: E501
        """DbsDbNameBody - a model defined in Swagger"""  # noqa: E501
        self._display_name = None
        self._branch_name = None
        self._ui = None
        self._metadata = None
        self.discriminator = None
        if display_name is not None:
            self.display_name = display_name
        if branch_name is not None:
            self.branch_name = branch_name
        if ui is not None:
            self.ui = ui
        if metadata is not None:
            self.metadata = metadata

    @property
    def display_name(self):
        """Gets the display_name of this DbsDbNameBody.  # noqa: E501


        :return: The display_name of this DbsDbNameBody.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this DbsDbNameBody.


        :param display_name: The display_name of this DbsDbNameBody.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def branch_name(self):
        """Gets the branch_name of this DbsDbNameBody.  # noqa: E501


        :return: The branch_name of this DbsDbNameBody.  # noqa: E501
        :rtype: str
        """
        return self._branch_name

    @branch_name.setter
    def branch_name(self, branch_name):
        """Sets the branch_name of this DbsDbNameBody.


        :param branch_name: The branch_name of this DbsDbNameBody.  # noqa: E501
        :type: str
        """

        self._branch_name = branch_name

    @property
    def ui(self):
        """Gets the ui of this DbsDbNameBody.  # noqa: E501


        :return: The ui of this DbsDbNameBody.  # noqa: E501
        :rtype: DbsdbNameUi
        """
        return self._ui

    @ui.setter
    def ui(self, ui):
        """Sets the ui of this DbsDbNameBody.


        :param ui: The ui of this DbsDbNameBody.  # noqa: E501
        :type: DbsdbNameUi
        """

        self._ui = ui

    @property
    def metadata(self):
        """Gets the metadata of this DbsDbNameBody.  # noqa: E501


        :return: The metadata of this DbsDbNameBody.  # noqa: E501
        :rtype: BranchMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this DbsDbNameBody.


        :param metadata: The metadata of this DbsDbNameBody.  # noqa: E501
        :type: BranchMetadata
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DbsDbNameBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DbsDbNameBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
