# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2012(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'xata': 'InlineResponse2012Xata'
    }

    attribute_map = {
        'id': 'id',
        'xata': 'xata'
    }

    def __init__(self, id=None, xata=None):  # noqa: E501
        """InlineResponse2012 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._xata = None
        self.discriminator = None
        self.id = id
        self.xata = xata

    @property
    def id(self):
        """Gets the id of this InlineResponse2012.  # noqa: E501


        :return: The id of this InlineResponse2012.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2012.


        :param id: The id of this InlineResponse2012.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def xata(self):
        """Gets the xata of this InlineResponse2012.  # noqa: E501


        :return: The xata of this InlineResponse2012.  # noqa: E501
        :rtype: InlineResponse2012Xata
        """
        return self._xata

    @xata.setter
    def xata(self, xata):
        """Sets the xata of this InlineResponse2012.


        :param xata: The xata of this InlineResponse2012.  # noqa: E501
        :type: InlineResponse2012Xata
        """
        if xata is None:
            raise ValueError("Invalid value for `xata`, must not be `None`")  # noqa: E501

        self._xata = xata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2012, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2012):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
