# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001Workspaces(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'WorkspaceID',
        'name': 'str',
        'slug': 'str',
        'role': 'Role'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'slug': 'slug',
        'role': 'role'
    }

    def __init__(self, id=None, name=None, slug=None, role=None):  # noqa: E501
        """InlineResponse2001Workspaces - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._slug = None
        self._role = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.slug = slug
        self.role = role

    @property
    def id(self):
        """Gets the id of this InlineResponse2001Workspaces.  # noqa: E501


        :return: The id of this InlineResponse2001Workspaces.  # noqa: E501
        :rtype: WorkspaceID
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2001Workspaces.


        :param id: The id of this InlineResponse2001Workspaces.  # noqa: E501
        :type: WorkspaceID
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this InlineResponse2001Workspaces.  # noqa: E501


        :return: The name of this InlineResponse2001Workspaces.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2001Workspaces.


        :param name: The name of this InlineResponse2001Workspaces.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def slug(self):
        """Gets the slug of this InlineResponse2001Workspaces.  # noqa: E501


        :return: The slug of this InlineResponse2001Workspaces.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this InlineResponse2001Workspaces.


        :param slug: The slug of this InlineResponse2001Workspaces.  # noqa: E501
        :type: str
        """
        if slug is None:
            raise ValueError("Invalid value for `slug`, must not be `None`")  # noqa: E501

        self._slug = slug

    @property
    def role(self):
        """Gets the role of this InlineResponse2001Workspaces.  # noqa: E501


        :return: The role of this InlineResponse2001Workspaces.  # noqa: E501
        :rtype: Role
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this InlineResponse2001Workspaces.


        :param role: The role of this InlineResponse2001Workspaces.  # noqa: E501
        :type: Role
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001Workspaces, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001Workspaces):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
