# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2011(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'database_name': 'str',
        'branch_name': 'str'
    }

    attribute_map = {
        'database_name': 'databaseName',
        'branch_name': 'branchName'
    }

    def __init__(self, database_name=None, branch_name=None):  # noqa: E501
        """InlineResponse2011 - a model defined in Swagger"""  # noqa: E501
        self._database_name = None
        self._branch_name = None
        self.discriminator = None
        self.database_name = database_name
        if branch_name is not None:
            self.branch_name = branch_name

    @property
    def database_name(self):
        """Gets the database_name of this InlineResponse2011.  # noqa: E501


        :return: The database_name of this InlineResponse2011.  # noqa: E501
        :rtype: str
        """
        return self._database_name

    @database_name.setter
    def database_name(self, database_name):
        """Sets the database_name of this InlineResponse2011.


        :param database_name: The database_name of this InlineResponse2011.  # noqa: E501
        :type: str
        """
        if database_name is None:
            raise ValueError("Invalid value for `database_name`, must not be `None`")  # noqa: E501

        self._database_name = database_name

    @property
    def branch_name(self):
        """Gets the branch_name of this InlineResponse2011.  # noqa: E501


        :return: The branch_name of this InlineResponse2011.  # noqa: E501
        :rtype: str
        """
        return self._branch_name

    @branch_name.setter
    def branch_name(self, branch_name):
        """Sets the branch_name of this InlineResponse2011.


        :param branch_name: The branch_name of this InlineResponse2011.  # noqa: E501
        :type: str
        """

        self._branch_name = branch_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2011, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2011):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
