# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListDatabasesResponseDatabases(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'display_name': 'str',
        'created_at': 'datetime',
        'number_of_branches': 'int',
        'ui': 'ListDatabasesResponseUi'
    }

    attribute_map = {
        'name': 'name',
        'display_name': 'displayName',
        'created_at': 'createdAt',
        'number_of_branches': 'numberOfBranches',
        'ui': 'ui'
    }

    def __init__(self, name=None, display_name=None, created_at=None, number_of_branches=None, ui=None):  # noqa: E501
        """ListDatabasesResponseDatabases - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._display_name = None
        self._created_at = None
        self._number_of_branches = None
        self._ui = None
        self.discriminator = None
        self.name = name
        self.display_name = display_name
        self.created_at = created_at
        self.number_of_branches = number_of_branches
        if ui is not None:
            self.ui = ui

    @property
    def name(self):
        """Gets the name of this ListDatabasesResponseDatabases.  # noqa: E501

        The machine-readable name of a database  # noqa: E501

        :return: The name of this ListDatabasesResponseDatabases.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ListDatabasesResponseDatabases.

        The machine-readable name of a database  # noqa: E501

        :param name: The name of this ListDatabasesResponseDatabases.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def display_name(self):
        """Gets the display_name of this ListDatabasesResponseDatabases.  # noqa: E501

        The human-readable name of a database  # noqa: E501

        :return: The display_name of this ListDatabasesResponseDatabases.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ListDatabasesResponseDatabases.

        The human-readable name of a database  # noqa: E501

        :param display_name: The display_name of this ListDatabasesResponseDatabases.  # noqa: E501
        :type: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def created_at(self):
        """Gets the created_at of this ListDatabasesResponseDatabases.  # noqa: E501


        :return: The created_at of this ListDatabasesResponseDatabases.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ListDatabasesResponseDatabases.


        :param created_at: The created_at of this ListDatabasesResponseDatabases.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def number_of_branches(self):
        """Gets the number_of_branches of this ListDatabasesResponseDatabases.  # noqa: E501

        The number of branches the database has  # noqa: E501

        :return: The number_of_branches of this ListDatabasesResponseDatabases.  # noqa: E501
        :rtype: int
        """
        return self._number_of_branches

    @number_of_branches.setter
    def number_of_branches(self, number_of_branches):
        """Sets the number_of_branches of this ListDatabasesResponseDatabases.

        The number of branches the database has  # noqa: E501

        :param number_of_branches: The number_of_branches of this ListDatabasesResponseDatabases.  # noqa: E501
        :type: int
        """
        if number_of_branches is None:
            raise ValueError("Invalid value for `number_of_branches`, must not be `None`")  # noqa: E501

        self._number_of_branches = number_of_branches

    @property
    def ui(self):
        """Gets the ui of this ListDatabasesResponseDatabases.  # noqa: E501


        :return: The ui of this ListDatabasesResponseDatabases.  # noqa: E501
        :rtype: ListDatabasesResponseUi
        """
        return self._ui

    @ui.setter
    def ui(self, ui):
        """Sets the ui of this ListDatabasesResponseDatabases.


        :param ui: The ui of this ListDatabasesResponseDatabases.  # noqa: E501
        :type: ListDatabasesResponseUi
        """

        self._ui = ui

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListDatabasesResponseDatabases, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListDatabasesResponseDatabases):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
