# coding: utf-8

"""
    xata

    xata.io API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkspaceInvite(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'invite_id': 'InviteID',
        'email': 'str',
        'expires': 'datetime',
        'role': 'Role'
    }

    attribute_map = {
        'invite_id': 'inviteId',
        'email': 'email',
        'expires': 'expires',
        'role': 'role'
    }

    def __init__(self, invite_id=None, email=None, expires=None, role=None):  # noqa: E501
        """WorkspaceInvite - a model defined in Swagger"""  # noqa: E501
        self._invite_id = None
        self._email = None
        self._expires = None
        self._role = None
        self.discriminator = None
        self.invite_id = invite_id
        self.email = email
        self.expires = expires
        self.role = role

    @property
    def invite_id(self):
        """Gets the invite_id of this WorkspaceInvite.  # noqa: E501


        :return: The invite_id of this WorkspaceInvite.  # noqa: E501
        :rtype: InviteID
        """
        return self._invite_id

    @invite_id.setter
    def invite_id(self, invite_id):
        """Sets the invite_id of this WorkspaceInvite.


        :param invite_id: The invite_id of this WorkspaceInvite.  # noqa: E501
        :type: InviteID
        """
        if invite_id is None:
            raise ValueError("Invalid value for `invite_id`, must not be `None`")  # noqa: E501

        self._invite_id = invite_id

    @property
    def email(self):
        """Gets the email of this WorkspaceInvite.  # noqa: E501


        :return: The email of this WorkspaceInvite.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this WorkspaceInvite.


        :param email: The email of this WorkspaceInvite.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def expires(self):
        """Gets the expires of this WorkspaceInvite.  # noqa: E501


        :return: The expires of this WorkspaceInvite.  # noqa: E501
        :rtype: datetime
        """
        return self._expires

    @expires.setter
    def expires(self, expires):
        """Sets the expires of this WorkspaceInvite.


        :param expires: The expires of this WorkspaceInvite.  # noqa: E501
        :type: datetime
        """
        if expires is None:
            raise ValueError("Invalid value for `expires`, must not be `None`")  # noqa: E501

        self._expires = expires

    @property
    def role(self):
        """Gets the role of this WorkspaceInvite.  # noqa: E501


        :return: The role of this WorkspaceInvite.  # noqa: E501
        :rtype: Role
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this WorkspaceInvite.


        :param role: The role of this WorkspaceInvite.  # noqa: E501
        :type: Role
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkspaceInvite, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkspaceInvite):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
